# Generated by Django 3.2.6 on 2021-10-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20211015_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
