# Generated by Django 3.2.6 on 2021-09-26 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automator', '0003_userprofile_profilepic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic_url',
            field=models.TextField(blank=True, default='https://rpgplanner.com/wp-content/uploads/2020/06/no-photo-available.png'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
