# Generated by Django 3.2.6 on 2021-09-28 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automator', '0004_auto_20210926_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_string', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(choices=[('None', '-NONE-'), ('JavaScript', 'JavaScript'), ('PHP', 'PHP'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Groovy', 'Groovy'), ('Perl', 'Perl'), ('Lua', 'Lua'), ('Bash', 'Bash'), ('PowerShell', 'PowerShell'), ('R', 'R'), ('VBA', 'VBA'), ('Emacs Lisp', 'Emacs Lisp'), ('GML', 'GML')], default='None', max_length=90)),
                ('platform', models.CharField(choices=[('None', '-NONE-'), ('Windows10x86', 'Windows 10 (32-bit)'), ('Windows10x64', 'Windows 10 (64-bit)'), ('Windows7x86', 'Windows 7 (32-bit)'), ('Windows7x64', 'Windows 7 (64-bit)'), ('Ubuntu', 'Ubuntu'), ('KaliLinux', 'Kali Linux'), ('macOS', 'macOS'), ('RaspbianOS', 'Raspbian OS')], default='None', max_length=90)),
                ('github_repo_URL', models.TextField()),
                ('brief_explanation', models.TextField(max_length=150)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('commands', models.ManyToManyField(related_name='automation', to='automator.Command')),
            ],
        ),
    ]
