# Generated by Django 3.2.6 on 2021-10-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automator', '0005_automation_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='readme',
            field=models.TextField(blank=True, default=''),
        ),
    ]
